# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/game.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10proto/game.proto\"*\n\x06Player\x12\n\n\x02id\x18\x01 \x01(\x05\x12\t\n\x01x\x18\x02 \x01(\x05\x12\t\n\x01y\x18\x03 \x01(\x05\"\x07\n\x05Hello\"\x12\n\x04Ping\x12\n\n\x02id\x18\x01 \x01(\x05\"0\n\x0c\x43lientUpdate\x12\n\n\x02id\x18\x01 \x01(\x05\x12\t\n\x01x\x18\x02 \x01(\x05\x12\t\n\x01y\x18\x03 \x01(\x05\"\x15\n\x07Welcome\x12\n\n\x02id\x18\x01 \x01(\x05\"P\n\x0bStatePacket\x12\x19\n\x05state\x18\x01 \x01(\x0e\x32\n.GameState\x12\x0c\n\x04tick\x18\x02 \x01(\x05\x12\x18\n\x07players\x18\x03 \x03(\x0b\x32\x07.Player\"\xae\x01\n\x06Packet\x12\x17\n\x05hello\x18\x01 \x01(\x0b\x32\x06.HelloH\x00\x12\x15\n\x04ping\x18\x02 \x01(\x0b\x32\x05.PingH\x00\x12&\n\rclient_update\x18\x03 \x01(\x0b\x32\r.ClientUpdateH\x00\x12\x1b\n\x07welcome\x18\x04 \x01(\x0b\x32\x08.WelcomeH\x00\x12$\n\x0cstate_packet\x18\x05 \x01(\x0b\x32\x0c.StatePacketH\x00\x42\t\n\x07payload*=\n\tGameState\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x0b\n\x07WAITING\x10\x01\x12\x0b\n\x07STARTED\x10\x02\x12\t\n\x05\x45NDED\x10\x03\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.game_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GAMESTATE._serialized_start=425
  _GAMESTATE._serialized_end=486
  _PLAYER._serialized_start=20
  _PLAYER._serialized_end=62
  _HELLO._serialized_start=64
  _HELLO._serialized_end=71
  _PING._serialized_start=73
  _PING._serialized_end=91
  _CLIENTUPDATE._serialized_start=93
  _CLIENTUPDATE._serialized_end=141
  _WELCOME._serialized_start=143
  _WELCOME._serialized_end=164
  _STATEPACKET._serialized_start=166
  _STATEPACKET._serialized_end=246
  _PACKET._serialized_start=249
  _PACKET._serialized_end=423
# @@protoc_insertion_point(module_scope)
